name: Deploy Functions on Push

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Functions Dependencies
        run: |
          cd functions
          npm ci

      - name: Run Backend Tests
        run: |
          cd functions
          npm run test

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
